title: CBICi5-Scratch-1-Skills-Link
hero_image: images/banner.png
description: CBICi5-Scratch-1-Skills-Link description
version: 4
listed: false
copyedit: false
last_tested: "2019-08-14"
steps:
  - title: Introduction
  - title: Step title
  - title: What next?
